const products = [
  {
    id: 1,
    name: "Smartphone Pro Max",
    description:
      "Smartphone dengan layar AMOLED 6.7 inci dan prosesor octa-core.",
    category: "smartphone",
    reviews: 234,
    rating: 4.5,
    price: 999.99,
    sold: 1500,
    stock: true,
    image: "smartphone_pro_max.jpg",
  },
  {
    id: 2,
    name: "Smartphone Lite",
    description: "Smartphone dengan layar 5.5 inci dan baterai tahan lama.",
    category: "smartphone",
    reviews: 123,
    rating: 4.0,
    price: 499.99,
    sold: 800,
    stock: false,
    image: "smartphone_lite.jpg",
  },
  {
    id: 3,
    name: "Smartphone Ultra",
    description: "Smartphone premium dengan tiga kamera dan layar HDR.",
    category: "smartphone",
    reviews: 345,
    rating: 4.7,
    price: 1099.99,
    sold: 1200,
    stock: true,
    image: "smartphone_ultra.jpg",
  },
  {
    id: 4,
    name: "Smartphone Economy",
    description: "Smartphone ekonomis dengan fitur standar.",
    category: "smartphone",
    reviews: 90,
    rating: 3.8,
    price: 299.99,
    sold: 500,
    stock: true,
    image: "smartphone_economy.jpg",
  },
  {
    id: 5,
    name: "Smartphone Mini",
    description: "Smartphone kecil dengan performa besar.",
    category: "smartphone",
    reviews: 190,
    rating: 4.3,
    price: 399.99,
    sold: 700,
    stock: false,
    image: "smartphone_mini.jpg",
  },
  {
    id: 6,
    name: "Smartphone Rugged",
    description: "Smartphone tahan banting dan air untuk petualangan ekstrem.",
    category: "smartphone",
    reviews: 80,
    rating: 4.1,
    price: 599.99,
    sold: 300,
    stock: true,
    image: "smartphone_rugged.jpg",
  },
  {
    id: 7,
    name: "Smartphone 5G",
    description: "Smartphone dengan konektivitas 5G super cepat.",
    category: "smartphone",
    reviews: 220,
    rating: 4.4,
    price: 899.99,
    sold: 1000,
    stock: true,
    image: "smartphone_5g.jpg",
  },
  {
    id: 8,
    name: "Smartphone Foldable",
    description: "Smartphone lipat dengan teknologi canggih.",
    category: "smartphone",
    reviews: 95,
    rating: 4.2,
    price: 1499.99,
    sold: 400,
    stock: true,
    image: "smartphone_foldable.jpg",
  },
  {
    id: 9,
    name: "Smartphone Gaming",
    description: "Smartphone khusus gaming dengan layar refresh rate tinggi.",
    category: "smartphone",
    reviews: 310,
    rating: 4.6,
    price: 799.99,
    sold: 900,
    stock: true,
    image: "smartphone_gaming.jpg",
  },
  {
    id: 10,
    name: "Smartphone Standard",
    description: "Smartphone dengan fitur dasar dan harga terjangkau.",
    category: "smartphone",
    reviews: 50,
    rating: 3.5,
    price: 199.99,
    sold: 250,
    stock: true,
    image: "smartphone_standard.jpg",
  },

  {
    id: 11,
    name: "Laptop UltraBook 2025",
    description: "Laptop dengan Intel Core i7 generasi terbaru dan SSD 1TB.",
    category: "laptop/computer",
    reviews: 542,
    rating: 4.8,
    price: 1299.99,
    sold: 850,
    stock: true,
    image: "laptop_ultrabook_2025.jpg",
  },
  {
    id: 12,
    name: "Laptop Gaming X",
    description: "Laptop gaming dengan grafis RTX 3080.",
    category: "laptop/computer",
    reviews: 350,
    rating: 4.9,
    price: 1799.99,
    sold: 600,
    stock: true,
    image: "laptop_gaming_x.jpg",
  },
  {
    id: 13,
    name: "Laptop Budget 2025",
    description: "Laptop ekonomis untuk kebutuhan sehari-hari.",
    category: "laptop/computer",
    reviews: 200,
    rating: 4.0,
    price: 599.99,
    sold: 700,
    stock: true,
    image: "laptop_budget_2025.jpg",
  },
  {
    id: 14,
    name: "Desktop All-in-One Z",
    description: "Komputer all-in-one dengan layar 24 inci.",
    category: "laptop/computer",
    reviews: 180,
    rating: 4.5,
    price: 899.99,
    sold: 500,
    stock: true,
    image: "desktop_all_in_one_z.jpg",
  },
  {
    id: 15,
    name: "Laptop Ultralight",
    description: "Laptop ringan dengan daya tahan baterai 12 jam.",
    category: "laptop/computer",
    reviews: 300,
    rating: 4.6,
    price: 1299.99,
    sold: 650,
    stock: true,
    image: "laptop_ultralight.jpg",
  },
  {
    id: 16,
    name: "Workstation Pro",
    description: "Workstation untuk kebutuhan profesional.",
    category: "laptop/computer",
    reviews: 250,
    rating: 4.7,
    price: 1999.99,
    sold: 400,
    stock: true,
    image: "workstation_pro.jpg",
  },
  {
    id: 17,
    name: "Mini PC Cube",
    description: "PC mini dengan performa besar.",
    category: "laptop/computer",
    reviews: 220,
    rating: 4.4,
    price: 499.99,
    sold: 300,
    stock: true,
    image: "mini_pc_cube.jpg",
  },
  {
    id: 18,
    name: "Laptop Convertible",
    description: "Laptop convertible dengan layar sentuh.",
    category: "laptop/computer",
    reviews: 320,
    rating: 4.6,
    price: 1099.99,
    sold: 450,
    stock: true,
    image: "laptop_convertible.jpg",
  },
  {
    id: 19,
    name: "Chromebook Z",
    description: "Laptop Chromebook untuk kebutuhan online.",
    category: "laptop/computer",
    reviews: 100,
    rating: 4.0,
    price: 399.99,
    sold: 200,
    stock: true,
    image: "chromebook_z.jpg",
  },
  {
    id: 20,
    name: "Laptop Studio Pro",
    description: "Laptop untuk desainer grafis dan video editor.",
    category: "laptop/computer",
    reviews: 400,
    rating: 4.8,
    price: 2199.99,
    sold: 500,
    stock: true,
    image: "laptop_studio_pro.jpg",
  },
];

export default products;
